<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Aakriti Poudel">
<meta name="dcterms.date" content="2026-05-08">

<title>Week 6: LDA Topic Modeling with Nexis Uni Data</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="assignment_w6_nexis_uni_files/libs/clipboard/clipboard.min.js"></script>
<script src="assignment_w6_nexis_uni_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="assignment_w6_nexis_uni_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="assignment_w6_nexis_uni_files/libs/quarto-html/popper.min.js"></script>
<script src="assignment_w6_nexis_uni_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="assignment_w6_nexis_uni_files/libs/quarto-html/anchor.min.js"></script>
<link href="assignment_w6_nexis_uni_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="assignment_w6_nexis_uni_files/libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="assignment_w6_nexis_uni_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="assignment_w6_nexis_uni_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="assignment_w6_nexis_uni_files/libs/bootstrap/bootstrap-769b268fb290e116fe386cf5612ac759.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#about-the-data" id="toc-about-the-data" class="nav-link active" data-scroll-target="#about-the-data">About the Data</a></li>
  <li><a href="#background-latent-dirichlet-allocation" id="toc-background-latent-dirichlet-allocation" class="nav-link" data-scroll-target="#background-latent-dirichlet-allocation">Background: Latent Dirichlet Allocation</a>
  <ul class="collapse">
  <li><a href="#how-the-model-imagines-text-was-written" id="toc-how-the-model-imagines-text-was-written" class="nav-link" data-scroll-target="#how-the-model-imagines-text-was-written">How the Model Imagines Text Was Written</a></li>
  <li><a href="#the-dirichlet-distribution" id="toc-the-dirichlet-distribution" class="nav-link" data-scroll-target="#the-dirichlet-distribution">The Dirichlet Distribution</a></li>
  </ul></li>
  <li><a href="#setup" id="toc-setup" class="nav-link" data-scroll-target="#setup">Setup</a></li>
  <li><a href="#load-the-data" id="toc-load-the-data" class="nav-link" data-scroll-target="#load-the-data">Load the Data</a></li>
  <li><a href="#build-the-corpus" id="toc-build-the-corpus" class="nav-link" data-scroll-target="#build-the-corpus">Build the Corpus</a></li>
  <li><a href="#tokenize-and-clean" id="toc-tokenize-and-clean" class="nav-link" data-scroll-target="#tokenize-and-clean">Tokenize and Clean</a></li>
  <li><a href="#build-the-document-feature-matrix" id="toc-build-the-document-feature-matrix" class="nav-link" data-scroll-target="#build-the-document-feature-matrix">Build the Document-Feature Matrix</a></li>
  <li><a href="#step-1-initial-model-theory-driven-k" id="toc-step-1-initial-model-theory-driven-k" class="nav-link" data-scroll-target="#step-1-initial-model-theory-driven-k">Step 1: Initial Model (Theory-Driven k)</a>
  <ul class="collapse">
  <li><a href="#inspect-the-posterior-distributions" id="toc-inspect-the-posterior-distributions" class="nav-link" data-scroll-target="#inspect-the-posterior-distributions">Inspect the Posterior Distributions</a></li>
  </ul></li>
  <li><a href="#step-2-selecting-k-with-coherence-scores" id="toc-step-2-selecting-k-with-coherence-scores" class="nav-link" data-scroll-target="#step-2-selecting-k-with-coherence-scores">Step 2: Selecting k with Coherence Scores</a></li>
  <li><a href="#step-3-fit-the-selected-model" id="toc-step-3-fit-the-selected-model" class="nav-link" data-scroll-target="#step-3-fit-the-selected-model">Step 3: Fit the Selected Model</a></li>
  <li><a href="#step-4-visualize-top-terms-per-topic" id="toc-step-4-visualize-top-terms-per-topic" class="nav-link" data-scroll-target="#step-4-visualize-top-terms-per-topic">Step 4: Visualize Top Terms per Topic</a></li>
  <li><a href="#step-5-name-the-topics" id="toc-step-5-name-the-topics" class="nav-link" data-scroll-target="#step-5-name-the-topics">Step 5: Name the Topics</a></li>
  <li><a href="#step-6-document-topic-distributions-θ" id="toc-step-6-document-topic-distributions-θ" class="nav-link" data-scroll-target="#step-6-document-topic-distributions-θ">Step 6: Document-Topic Distributions (θ)</a></li>
  <li><a href="#step-7-interactive-visualization-with-ldavis" id="toc-step-7-interactive-visualization-with-ldavis" class="nav-link" data-scroll-target="#step-7-interactive-visualization-with-ldavis">Step 7: Interactive Visualization with LDAvis</a>
  <ul class="collapse">
  <li><a href="#the-λ-lambda-relevance-parameter" id="toc-the-λ-lambda-relevance-parameter" class="nav-link" data-scroll-target="#the-λ-lambda-relevance-parameter">The λ (lambda) Relevance Parameter</a></li>
  </ul></li>
  <li><a href="#interpretation" id="toc-interpretation" class="nav-link" data-scroll-target="#interpretation">Interpretation</a>
  <ul class="collapse">
  <li><a href="#build-and-clean-your-corpus" id="toc-build-and-clean-your-corpus" class="nav-link" data-scroll-target="#build-and-clean-your-corpus">1. Build and Clean Your Corpus</a></li>
  <li><a href="#select-k-using-multiple-criteria" id="toc-select-k-using-multiple-criteria" class="nav-link" data-scroll-target="#select-k-using-multiple-criteria">2. Select k Using Multiple Criteria</a></li>
  <li><a href="#final-model-and-top-terms-plot" id="toc-final-model-and-top-terms-plot" class="nav-link" data-scroll-target="#final-model-and-top-terms-plot">3. Final Model and Top Terms Plot</a></li>
  <li><a href="#document-topic-distributions" id="toc-document-topic-distributions" class="nav-link" data-scroll-target="#document-topic-distributions">4. Document-Topic Distributions</a></li>
  <li><a href="#interpret-your-topics" id="toc-interpret-your-topics" class="nav-link" data-scroll-target="#interpret-your-topics">5. Interpret Your Topics</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Week 6: LDA Topic Modeling with Nexis Uni Data</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Aakriti Poudel </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 8, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="about-the-data" class="level2">
<h2 class="anchored" data-anchor-id="about-the-data">About the Data</h2>
<p>The data for this analysis comes from <a href="https://www.library.ucsb.edu/">Nexis Uni</a>, a news database available through the UCSB Library. To collect the articles, I searched the keyword <strong>“wild fire”</strong> in the News category and selected <strong>100 articles</strong> for download in Word (.DOCX) format.</p>
<p>The search was not restricted to a specific country, date range, or news source, so the corpus includes articles from a range of international outlets. This matters for interpreting the topics – because the corpus is global rather than focused on a single region, the model surfaces geographic subthemes such as Scottish fire response or Nigerian fire incidents as separate topics, rather than grouping all articles under one broad wildfire theme.</p>
<p>The final corpus contains <strong>100 articles</strong> (as shown in the <code>glimpse()</code> output below).</p>
<hr>
</section>
<section id="background-latent-dirichlet-allocation" class="level2">
<h2 class="anchored" data-anchor-id="background-latent-dirichlet-allocation">Background: Latent Dirichlet Allocation</h2>
<p><strong>Latent Dirichlet Allocation (LDA)</strong> is a method for discovering hidden themes (called <em>topics</em>) in a collection of text documents. Each document is treated as a mix of topics, and each topic is a mix of words. The model works backwards from the words it can see to figure out what topics were likely involved. Understanding the key variables helps interpret the results:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 39%">
<col style="width: 30%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th>Symbol</th>
<th>Name</th>
<th>What it means</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>α</strong> (alpha)</td>
<td>Hyperparameter</td>
<td>Controls how many topics a single document tends to cover. A small value means each document focuses on just one or two topics. Set by the researcher.</td>
</tr>
<tr class="even">
<td><strong>β</strong> (beta)</td>
<td>Hyperparameter</td>
<td>Controls how many words each topic tends to use. A small value means each topic has a tight, focused vocabulary. Set by the researcher.</td>
</tr>
<tr class="odd">
<td><strong>θ</strong> (theta)</td>
<td>Document-topic mix</td>
<td>The estimated proportion of each topic in a given document – i.e., how much of document X is about topic Y. Has to be estimated from the data.</td>
</tr>
<tr class="even">
<td><strong>φ</strong> (phi)</td>
<td>Topic-word mix</td>
<td>The estimated probability of each word belonging to a given topic – i.e., how strongly word W is associated with topic T. Called <code>beta</code> in tidytext. Has to be estimated from the data.</td>
</tr>
<tr class="odd">
<td><strong>z</strong></td>
<td>Topic assignment</td>
<td>The hidden topic label attached to each individual word. Connects the document-topic and topic-word distributions. Has to be estimated from the data.</td>
</tr>
<tr class="even">
<td><strong>w</strong></td>
<td>Observed word</td>
<td>The only thing you actually see. Everything else (z, θ, φ) is estimated from patterns in w.</td>
</tr>
</tbody>
</table>
<section id="how-the-model-imagines-text-was-written" class="level3">
<h3 class="anchored" data-anchor-id="how-the-model-imagines-text-was-written">How the Model Imagines Text Was Written</h3>
<p>LDA assumes that documents were written as follows:</p>
<ol type="1">
<li>For each topic <em>t</em>, draw a word distribution <strong>φ_t</strong> ~ Dirichlet(β)</li>
<li>For each document <em>m</em>, draw a topic distribution <strong>θ_m</strong> ~ Dirichlet(α)</li>
<li>For each word position in that document:
<ul>
<li>Draw a topic assignment <strong>z</strong> ~ Multinomial(θ_m)</li>
<li>Draw the word <strong>w</strong> ~ Multinomial(φ_z)</li>
</ul></li>
</ol>
<p>In practice, we only observe the words (<strong>w</strong>). The model runs this process in reverse to estimate the most likely <strong>z</strong>, <strong>θ</strong>, and <strong>φ</strong>.</p>
</section>
<section id="the-dirichlet-distribution" class="level3">
<h3 class="anchored" data-anchor-id="the-dirichlet-distribution">The Dirichlet Distribution</h3>
<p>The Dirichlet distribution produces probability vectors that sum to 1, ideal for representing mixtures of topics or words. The concentration parameter (α or β) controls how spread out the mixture is:</p>
<ul>
<li><strong>Small value (&lt; 1)</strong>: most probability sits on one or two categories, realistic for most text.</li>
<li><strong>Large value (&gt; 1)</strong>: probability is spread evenly across all categories.</li>
<li><strong>Value = 1</strong>: all mixtures are equally likely.</li>
</ul>
<hr>
</section>
</section>
<section id="setup" class="level2">
<h2 class="anchored" data-anchor-id="setup">Setup</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(LexisNexisTools)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(quanteda)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tm)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(topicmodels)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(topicdoc)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidytext)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(reshape2)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tictoc)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(LDAvis)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tsne)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(servr)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(slam)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="load-the-data" class="level2">
<h2 class="anchored" data-anchor-id="load-the-data">Load the Data</h2>
<p>We use <code>{LexisNexisTools}</code> to parse the Nexis Uni <code>.DOCX</code> export. This package understands the specific formatting Nexis Uni uses and splits the file into separate articles with metadata like date, headline, and source.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set path to the Nexis Uni data file</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>pre_files <span class="ot">&lt;-</span> <span class="st">"assignments/data/nexis_uni_wild-fire_data.DOCX"</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Parse the Nexis Uni export into structured slots</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>pre_dat <span class="ot">&lt;-</span> <span class="fu">lnt_read</span>(pre_files)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract metadata, article text, and paragraph-level data</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>pre_meta_df       <span class="ot">&lt;-</span> pre_dat<span class="sc">@</span>meta</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>pre_articles_df   <span class="ot">&lt;-</span> pre_dat<span class="sc">@</span>articles</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>pre_paragraphs_df <span class="ot">&lt;-</span> pre_dat<span class="sc">@</span>paragraphs</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Build a clean data frame with one row per article</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>tbl <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">date     =</span> pre_meta_df<span class="sc">$</span>Date,</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">headline =</span> pre_meta_df<span class="sc">$</span>Headline,</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">id       =</span> pre_meta_df<span class="sc">$</span>ID,</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">text     =</span> pre_articles_df<span class="sc">$</span>Article,</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">source   =</span> pre_meta_df<span class="sc">$</span>Newspaper</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(tbl)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 100
Columns: 5
$ date     &lt;date&gt; 2026-03-18, 2025-12-31, 2025-12-31, 2026-02-12, 2026-04-10, …
$ headline &lt;chr&gt; "Wild fire razes homes in Kano, sparks safety warning", "27,0…
$ id       &lt;int&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18…
$ text     &lt;chr&gt; "Link to Image\nA fire outbreak has destroyed parts of three …
$ source   &lt;chr&gt; "The Daily Post (Nigeria)", "Daily Mirror", "Daily Mirror", "…</code></pre>
</div>
</div>
</section>
<section id="build-the-corpus" class="level2">
<h2 class="anchored" data-anchor-id="build-the-corpus">Build the Corpus</h2>
<p>We convert the data frame into a quanteda corpus object. Each row in <code>tbl</code> becomes one document in the corpus, which LDA will treat as a separate unit when estimating topic mixtures.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>corpus <span class="ot">&lt;-</span> <span class="fu">corpus</span>(<span class="at">x =</span> tbl, <span class="at">text_field =</span> <span class="st">"text"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="tokenize-and-clean" class="level2">
<h2 class="anchored" data-anchor-id="tokenize-and-clean">Tokenize and Clean</h2>
<p>Before modeling, we need to break the text into individual words (tokens) and remove words that carry no meaningful information about topic differences. We remove standard English stop words, common journalistic filler phrases, and generic wildfire terms. Words like “fire” and “wildfire” appear in nearly every article and would show up at the top of every topic without helping us understand what makes the topics different from each other. We also remove a stray backtick character (<code>`</code>) that can slip through as a tokenization artifact.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine standard stopwords with domain-specific ones</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>add_stops <span class="ot">&lt;-</span> <span class="fu">c</span>(quanteda<span class="sc">::</span><span class="fu">stopwords</span>(<span class="st">"en"</span>, <span class="at">source =</span> <span class="st">"smart"</span>),</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>               <span class="st">"said"</span>, <span class="st">"says"</span>, <span class="st">"told"</span>, <span class="st">"according"</span>,</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>               <span class="st">"fire"</span>, <span class="st">"fires"</span>, <span class="st">"wildfire"</span>, <span class="st">"wildfires"</span>,</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>               <span class="st">"`"</span>)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Tokenize, remove punctuation and numbers, then lowercase</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>toks <span class="ot">&lt;-</span> <span class="fu">tokens</span>(corpus, <span class="at">remove_punct =</span> <span class="cn">TRUE</span>, <span class="at">remove_numbers =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tokens_tolower</span>()</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove all stopwords</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>toks1 <span class="ot">&lt;-</span> <span class="fu">tokens_select</span>(toks, <span class="at">pattern =</span> add_stops, <span class="at">selection =</span> <span class="st">"remove"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="build-the-document-feature-matrix" class="level2">
<h2 class="anchored" data-anchor-id="build-the-document-feature-matrix">Build the Document-Feature Matrix</h2>
<p>LDA works on a document-feature matrix (DFM), which counts how many times each word appears in each document. We remove very rare words (appearing in fewer than 2 documents) since they add noise without helping identify shared topics. We also remove any documents that end up empty after trimming.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>dfm1 <span class="ot">&lt;-</span> <span class="fu">dfm</span>(toks1)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove words that appear in fewer than 2 documents</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>dfm2 <span class="ot">&lt;-</span> <span class="fu">dfm_trim</span>(dfm1, <span class="at">min_docfreq =</span> <span class="dv">2</span>)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove empty documents -- LDA cannot handle rows with zero tokens</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>sel_idx <span class="ot">&lt;-</span> slam<span class="sc">::</span><span class="fu">row_sums</span>(dfm2) <span class="sc">&gt;</span> <span class="dv">0</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>dfm     <span class="ot">&lt;-</span> dfm2[sel_idx, ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<hr>
</section>
<section id="step-1-initial-model-theory-driven-k" class="level2">
<h2 class="anchored" data-anchor-id="step-1-initial-model-theory-driven-k">Step 1: Initial Model (Theory-Driven k)</h2>
<p>Before using data to choose the number of topics, we start with a theory driven guess. For a wildfire news corpus, we might expect articles to cluster around a few broad themes: emergency response, climate and weather conditions, land management, and property damage. This gives us a starting point of k = 4.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>k <span class="ot">&lt;-</span> <span class="dv">4</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>topicModel_k4 <span class="ot">&lt;-</span> <span class="fu">LDA</span>(dfm,</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>                     k,</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>                     <span class="at">method  =</span> <span class="st">"Gibbs"</span>,</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>                     <span class="at">control =</span> <span class="fu">list</span>(<span class="at">iter    =</span> <span class="dv">100</span>,</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">verbose =</span> <span class="dv">25</span>,</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">seed    =</span> <span class="dv">321</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>K = 4; V = 2767; M = 100
Sampling 100 iterations!
Iteration 25 ...
Iteration 50 ...
Iteration 75 ...
Iteration 100 ...
Gibbs sampling completed!</code></pre>
</div>
</div>
<section id="inspect-the-posterior-distributions" class="level3">
<h3 class="anchored" data-anchor-id="inspect-the-posterior-distributions">Inspect the Posterior Distributions</h3>
<p><code>posterior()</code> extracts the two key output matrices:</p>
<ul>
<li><strong>theta (θ)</strong>: document × topic matrix, how much of each document belongs to each topic</li>
<li><strong>beta/phi (φ)</strong>: topic × term matrix, how strongly each word is associated with each topic</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>result <span class="ot">&lt;-</span> <span class="fu">posterior</span>(topicModel_k4)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>beta  <span class="ot">&lt;-</span> result<span class="sc">$</span>terms</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>theta <span class="ot">&lt;-</span> result<span class="sc">$</span>topics</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"phi dimensions  (topics x vocab):"</span>, <span class="fu">dim</span>(beta),  <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>phi dimensions  (topics x vocab): 4 2767 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"theta dimensions (docs x topics):"</span>, <span class="fu">dim</span>(theta), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>theta dimensions (docs x topics): 100 4 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Top 10 terms per topic</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">terms</span>(topicModel_k4, <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Topic 1        Topic 2      Topic 3       Topic 4  
 [1,] "service"      "forest"     "wild"        "wild"   
 [2,] "rescue"       "areas"      "property"    "area"   
 [3,] "firefighters" "conditions" "system"      "people" 
 [4,] "scottish"     "management" "services"    "time"   
 [5,] "crews"        "risk"       "liquid"      "smoke"  
 [6,] "incident"     "dry"        "network"     "cooking"
 [7,] "training"     "community"  "chemical"    "pizza"  
 [8,] "report"       "county"     "anti-fire"   "times"  
 [9,] "government"   "april"      "qep"         "air"    
[10,] "response"     "year"       "information" "site"   </code></pre>
</div>
</div>
<p>Looking at the top terms, we can see some early patterns. Topic 1 captures Scottish fire response terms like “rescue” and “scottish”, and Topic 4 shows general and unexpected words like “smoke”, “cooking”, and “pizza”. However, topics are quite mixed overall, for example “cooking” and “pizza” appear in Topic 4 alongside general news terms, while “qep” appears in Topic 3 alongside industrial terms like “liquid” and “chemical”, which are unrelated to each other. This suggests k = 4 is too few to cleanly separate the themes in this 100-article corpus.</p>
<hr>
</section>
</section>
<section id="step-2-selecting-k-with-coherence-scores" class="level2">
<h2 class="anchored" data-anchor-id="step-2-selecting-k-with-coherence-scores">Step 2: Selecting k with Coherence Scores</h2>
<p>Instead of relying only on theory, we can let the data help us choose k. We fit models for k = 2 through 15 and measure coherence for each. Coherence measures whether the top words in each topic actually appear together in the same articles, a sign that the topic is meaningful and not just a mix of unrelated words.</p>
<p><strong>Higher coherence (closer to 0) = more meaningful topics.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tic</span>()</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit one model for each value of k</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>k_values <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">2</span>, <span class="dv">15</span>, <span class="at">by =</span> <span class="dv">1</span>)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>coherence_results <span class="ot">&lt;-</span> <span class="fu">map_dfr</span>(k_values, <span class="cf">function</span>(k) {</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>  m <span class="ot">&lt;-</span> <span class="fu">LDA</span>(dfm, <span class="at">k =</span> k, <span class="at">method =</span> <span class="st">"Gibbs"</span>,</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>           <span class="at">control =</span> <span class="fu">list</span>(<span class="at">iter    =</span> <span class="dv">300</span>,</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>                          <span class="at">seed    =</span> <span class="dv">321</span>,</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>                          <span class="at">verbose =</span> <span class="dv">0</span>))</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Calculate mean coherence score for this k</span></span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>  coh <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">topic_coherence</span>(m, dfm))</span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tibble</span>(<span class="at">k =</span> k, <span class="at">coherence =</span> coh)</span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a><span class="fu">toc</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>1.887 sec elapsed</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot coherence vs k</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(coherence_results, <span class="fu">aes</span>(<span class="at">x =</span> k, <span class="at">y =</span> coherence)) <span class="sc">+</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">"navy"</span>) <span class="sc">+</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"navy"</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> coherence_results<span class="sc">$</span>k[<span class="fu">which.max</span>(coherence_results<span class="sc">$</span>coherence)],</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>             <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title    =</span> <span class="st">"Mean topic coherence by number of topics (k)"</span>,</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Dashed line = k with highest coherence"</span>,</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">x        =</span> <span class="st">"Number of topics (k)"</span>,</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">y        =</span> <span class="st">"Mean coherence score"</span>) <span class="sc">+</span></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="assignment_w6_nexis_uni_files/figure-html/find_k-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Full table of coherence scores</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>coherence_results</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 14 × 2
       k coherence
   &lt;dbl&gt;     &lt;dbl&gt;
 1     2     -68.7
 2     3     -77.2
 3     4     -67.6
 4     5     -63.1
 5     6     -66.1
 6     7     -65.5
 7     8     -62.4
 8     9     -59.0
 9    10     -59.3
10    11     -63.9
11    12     -61.7
12    13     -60.7
13    14     -59.2
14    15     -64.2</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p><strong>Interpreting the plot:</strong> Look for the peak coherence value, or an “elbow” where adding more topics stops improving coherence meaningfully. Also inspect the top terms at two or three candidate k values, statistical criteria and human interpretability do not always agree.</p>
</blockquote>
<p>The coherence plot peaks at <strong>k = 9</strong> (coherence = -59.0). The curve drops sharply from k = 2 to k = 3, then generally improves from k = 3 through k = 9, after which it becomes more variable. However, k = 9 is still more topics than needed for 100 articles and would likely create several near-identical groups.</p>
<p>We proceed with <strong>k = 6</strong> as a practical balance. While k = 7 (-65.5), k = 8 (-62.4), and the statistical peak k = 9 (-59.0) all have higher coherence scores than k = 6 (-66.1), at those values topics begin splitting closely related content into subtopics that are difficult to tell apart. At k = 6, each topic has a clean, distinct set of terms that points to a recognizable real-world theme.</p>
<hr>
</section>
<section id="step-3-fit-the-selected-model" class="level2">
<h2 class="anchored" data-anchor-id="step-3-fit-the-selected-model">Step 3: Fit the Selected Model</h2>
<p>We now fit the final model with k = 6, using more iterations (1000) for better convergence than the exploratory model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>k <span class="ot">&lt;-</span> <span class="dv">6</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>topicModel_k_select <span class="ot">&lt;-</span> <span class="fu">LDA</span>(dfm, k,</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>                           <span class="at">method  =</span> <span class="st">"Gibbs"</span>,</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>                           <span class="at">control =</span> <span class="fu">list</span>(<span class="at">iter    =</span> <span class="dv">1000</span>,</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>                                          <span class="at">verbose =</span> <span class="dv">25</span>,</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>                                          <span class="at">seed    =</span> <span class="dv">321</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>K = 6; V = 2767; M = 100
Sampling 1000 iterations!
Iteration 25 ...
Iteration 50 ...
Iteration 75 ...
Iteration 100 ...
Iteration 125 ...
Iteration 150 ...
Iteration 175 ...
Iteration 200 ...
Iteration 225 ...
Iteration 250 ...
Iteration 275 ...
Iteration 300 ...
Iteration 325 ...
Iteration 350 ...
Iteration 375 ...
Iteration 400 ...
Iteration 425 ...
Iteration 450 ...
Iteration 475 ...
Iteration 500 ...
Iteration 525 ...
Iteration 550 ...
Iteration 575 ...
Iteration 600 ...
Iteration 625 ...
Iteration 650 ...
Iteration 675 ...
Iteration 700 ...
Iteration 725 ...
Iteration 750 ...
Iteration 775 ...
Iteration 800 ...
Iteration 825 ...
Iteration 850 ...
Iteration 875 ...
Iteration 900 ...
Iteration 925 ...
Iteration 950 ...
Iteration 975 ...
Iteration 1000 ...
Gibbs sampling completed!</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract posterior distributions</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>tmResult <span class="ot">&lt;-</span> <span class="fu">posterior</span>(topicModel_k_select)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="fu">terms</span>(topicModel_k_select, <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Topic 1        Topic 2      Topic 3      Topic 4        Topic 5     
 [1,] "rescue"       "conditions" "forest"     "service"      "people"    
 [2,] "scottish"     "wild"       "management" "weather"      "qep"       
 [3,] "service"      "climate"    "areas"      "wild"         "news"      
 [4,] "government"   "time"       "local"      "dry"          "home"      
 [5,] "training"     "cooking"    "community"  "april"        "emergency" 
 [6,] "report"       "years"      "vegetation" "firefighters" "content"   
 [7,] "sfrs"         "solution"   "controlled" "country"      "california"
 [8,] "firefighters" "smoke"      "lives"      "crews"        "state"     
 [9,] "states"       "people"     "county"     "emergency"    "recovery"  
[10,] "blazes"       "support"    "risk"       "heat"         "disaster"  
      Topic 6    
 [1,] "wild"     
 [2,] "property" 
 [3,] "system"   
 [4,] "liquid"   
 [5,] "chemical" 
 [6,] "network"  
 [7,] "anti-fire"
 [8,] "area"     
 [9,] "spraying" 
[10,] "homes"    </code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>theta <span class="ot">&lt;-</span> tmResult<span class="sc">$</span>topics</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>beta  <span class="ot">&lt;-</span> tmResult<span class="sc">$</span>terms</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>vocab <span class="ot">&lt;-</span> <span class="fu">colnames</span>(beta)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<hr>
</section>
<section id="step-4-visualize-top-terms-per-topic" class="level2">
<h2 class="anchored" data-anchor-id="step-4-visualize-top-terms-per-topic">Step 4: Visualize Top Terms per Topic</h2>
<p>The β (φ) matrix gives us the probability of each word belonging to each topic. Plotting the highest-probability terms for each topic is the main tool for understanding what each topic is actually about.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>topics <span class="ot">&lt;-</span> <span class="fu">tidy</span>(topicModel_k_select, <span class="at">matrix =</span> <span class="st">"beta"</span>)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>top_terms <span class="ot">&lt;-</span> topics <span class="sc">|&gt;</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(topic) <span class="sc">|&gt;</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_max</span>(beta, <span class="at">n =</span> <span class="dv">10</span>) <span class="sc">|&gt;</span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">|&gt;</span></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(topic, <span class="sc">-</span>beta)</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>top_terms <span class="sc">|&gt;</span></span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">term =</span> <span class="fu">reorder_within</span>(term, beta, topic, <span class="at">sep =</span> <span class="st">""</span>)) <span class="sc">|&gt;</span></span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(term, beta, <span class="at">fill =</span> <span class="fu">factor</span>(topic))) <span class="sc">+</span></span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">show.legend =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> topic, <span class="at">scales =</span> <span class="st">"free_y"</span>) <span class="sc">+</span></span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_reordered</span>() <span class="sc">+</span></span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title    =</span> <span class="st">"Top 10 terms per topic"</span>,</span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"β = P(term | topic)"</span>,</span>
<span id="cb25-18"><a href="#cb25-18" aria-hidden="true" tabindex="-1"></a>       <span class="at">x        =</span> <span class="cn">NULL</span>,</span>
<span id="cb25-19"><a href="#cb25-19" aria-hidden="true" tabindex="-1"></a>       <span class="at">y        =</span> <span class="st">"β"</span>) <span class="sc">+</span></span>
<span id="cb25-20"><a href="#cb25-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="assignment_w6_nexis_uni_files/figure-html/top_terms_plot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<hr>
</section>
<section id="step-5-name-the-topics" class="level2">
<h2 class="anchored" data-anchor-id="step-5-name-the-topics">Step 5: Name the Topics</h2>
<p>We assign a label to each topic based on its top words. This step requires reading the terms and thinking about what real-world theme they point to.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>topic_words <span class="ot">&lt;-</span> <span class="fu">terms</span>(topicModel_k_select, <span class="dv">5</span>)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Assign a descriptive label to each topic</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Order matches the topic numbering from terms(topicModel_k_select, 10):</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Topic 1: rescue, scottish, service, government, training</span></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Topic 2: conditions, wild, climate, cooking, years</span></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Topic 3: forest, management, areas, local, community</span></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Topic 4: service, weather, wild, dry, april (firefighters, crews, heat)</span></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Topic 5: people, qep, news, home, emergency</span></span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Topic 6: wild, property, system, liquid, chemical</span></span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>topic_names <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Scottish Fire Response"</span>,</span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Climate &amp; Weather Conditions"</span>,</span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Vegetation &amp; Land Management"</span>,</span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Seasonal Fire &amp; Firefighter Response"</span>,</span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Disaster Recovery &amp; Community Impact"</span>,</span>
<span id="cb26-17"><a href="#cb26-17" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Industrial Fire Risk &amp; Technology"</span></span>
<span id="cb26-18"><a href="#cb26-18" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb26-19"><a href="#cb26-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-20"><a href="#cb26-20" aria-hidden="true" tabindex="-1"></a>topic_names</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Scottish Fire Response"              
[2] "Climate &amp; Weather Conditions"        
[3] "Vegetation &amp; Land Management"        
[4] "Seasonal Fire &amp; Firefighter Response"
[5] "Disaster Recovery &amp; Community Impact"
[6] "Industrial Fire Risk &amp; Technology"   </code></pre>
</div>
</div>
<hr>
</section>
<section id="step-6-document-topic-distributions-θ" class="level2">
<h2 class="anchored" data-anchor-id="step-6-document-topic-distributions-θ">Step 6: Document-Topic Distributions (θ)</h2>
<p>The θ matrix shows what proportion of each document belongs to each topic. A document focused entirely on one theme will have a high θ for that topic and near-zero values for the others. Mixed documents spread their weight across several topics.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Select the first 5 documents to examine</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>example_ids <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">length</span>(example_ids)</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>example_props <span class="ot">&lt;-</span> theta[example_ids, ]</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(example_props) <span class="ot">&lt;-</span> topic_names</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>viz_df <span class="ot">&lt;-</span> <span class="fu">melt</span>(<span class="fu">cbind</span>(<span class="fu">data.frame</span>(example_props),</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>                     <span class="at">document =</span> <span class="fu">factor</span>(<span class="dv">1</span><span class="sc">:</span>n)),</span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>               <span class="at">variable.name =</span> <span class="st">"topic"</span>,</span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>               <span class="at">id.vars =</span> <span class="st">"document"</span>)</span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> viz_df, <span class="fu">aes</span>(topic, value, <span class="at">fill =</span> document)) <span class="sc">+</span></span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>) <span class="sc">+</span></span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb28-16"><a href="#cb28-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>, <span class="at">hjust =</span> <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb28-17"><a href="#cb28-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb28-18"><a href="#cb28-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> document, <span class="at">ncol =</span> n) <span class="sc">+</span></span>
<span id="cb28-19"><a href="#cb28-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Topic distributions across sample documents"</span>,</span>
<span id="cb28-20"><a href="#cb28-20" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"θ = P(topic | document)"</span>,</span>
<span id="cb28-21"><a href="#cb28-21" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="cn">NULL</span>,</span>
<span id="cb28-22"><a href="#cb28-22" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Topic proportion"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="assignment_w6_nexis_uni_files/figure-html/topic_dists-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<hr>
</section>
<section id="step-7-interactive-visualization-with-ldavis" class="level2">
<h2 class="anchored" data-anchor-id="step-7-interactive-visualization-with-ldavis">Step 7: Interactive Visualization with LDAvis</h2>
<p>LDAvis provides an interactive view of two complementary aspects of the model:</p>
<ul>
<li><p><strong>Intertopic distance map</strong>: circles represent topics; size = proportion of corpus tokens assigned to that topic; distance = degree of topic overlap in vocabulary</p></li>
<li><p><strong>Term relevance bar chart</strong>: adjustable by the λ (lambda) parameter</p></li>
</ul>
<section id="the-λ-lambda-relevance-parameter" class="level3">
<h3 class="anchored" data-anchor-id="the-λ-lambda-relevance-parameter">The λ (lambda) Relevance Parameter</h3>
<p>λ controls how words are ranked within a topic:</p>
<p><span class="math display">\[\text{Relevance}(w, t) = \lambda \times P(w|t) + (1 - \lambda) \times \frac{P(w|t)}{P(w)}\]</span></p>
<ul>
<li><strong>λ near 1</strong>: ranks words by raw frequency within the topic, highlights common words</li>
<li><strong>λ near 0</strong>: ranks words by how <em>exclusive</em> they are to that topic relative to the whole corpus, highlights distinctive words</li>
<li><strong>λ = 0.6</strong>: the recommended starting point (Sievert &amp; Shirley, 2014) that balances both, <strong>use this, not the default λ = 1.0</strong></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>svd_tsne <span class="ot">&lt;-</span> <span class="cf">function</span>(x) <span class="fu">tsne</span>(<span class="fu">svd</span>(x)<span class="sc">$</span>u)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>json <span class="ot">&lt;-</span> <span class="fu">createJSON</span>(</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">phi            =</span> tmResult<span class="sc">$</span>terms,</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">theta          =</span> tmResult<span class="sc">$</span>topics,</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">doc.length     =</span> <span class="fu">rowSums</span>(dfm),</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">vocab          =</span> <span class="fu">colnames</span>(dfm),</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">term.frequency =</span> <span class="fu">colSums</span>(dfm),</span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">mds.method     =</span> svd_tsne,</span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">plot.opts      =</span> <span class="fu">list</span>(<span class="at">xlab =</span> <span class="st">""</span>, <span class="at">ylab =</span> <span class="st">""</span>)</span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">interactive</span>()) <span class="fu">serVis</span>(json)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<blockquote class="blockquote">
<p><strong>Reading the LDAvis plot:</strong> The intertopic distance map shows 6 circles of varying sizes. Topic 2 (Climate and Weather Conditions) and Topic 4 (Seasonal Fire and Firefighter Response) are among the largest circles, meaning they account for the biggest shares of the corpus. Topic 3 (Vegetation and Land Management) sits far to the left, well separated from the rest, which means it uses very different vocabulary from the other topics. Topic 6 (Industrial Fire Risk and Technology) sits near the center of the map. Topics 4 and 5 sit close together in the lower portion of the map, which makes sense since both cover community-level response and locally focused fire content. Topic 1 (Scottish Fire Response) sits near the center-left and is reasonably well separated from the other topics. Overall the separation is good, though the overlap between Topics 4 and 5 suggests those two could potentially be merged.</p>
</blockquote>
<hr>
</section>
</section>
<section id="interpretation" class="level2">
<h2 class="anchored" data-anchor-id="interpretation">Interpretation</h2>
<section id="build-and-clean-your-corpus" class="level3">
<h3 class="anchored" data-anchor-id="build-and-clean-your-corpus">1. Build and Clean Your Corpus</h3>
<p>The corpus was built from 100 Nexis Uni news articles retrieved using the keyword search <strong>“wild fire”</strong> in the News category, with no geographic or date filters applied. The file <code>nexis_uni_wild-fire_data.DOCX</code> was downloaded for this assignment and parsed using <code>{LexisNexisTools}</code>, covering international outlets.</p>
<p>Custom stop words were added in two groups. First, journalistic filler words (“said”, “says”, “told”, “according”) were removed because they appear across all articles regardless of topic. Second, the words “fire”, “fires”, “wildfire”, and “wildfires” were removed because they appear in nearly every article and would otherwise show up at the top of every topic, making it impossible to see what is actually different between them. A stray backtick character was also added to the stop word list to prevent a punctuation artifact from appearing in the top term lists.</p>
</section>
<section id="select-k-using-multiple-criteria" class="level3">
<h3 class="anchored" data-anchor-id="select-k-using-multiple-criteria">2. Select k Using Multiple Criteria</h3>
<p><strong>Theory:</strong> A wildfire news corpus covering international outlets is likely to contain articles on emergency response, land management, climate and weather conditions, industrial fire technology, community recovery, and specific geographic events. This suggests somewhere between 5 and 7 topics would capture the main themes across 100 articles.</p>
<p><strong>Optimization Metrics:</strong> The coherence plot peaks at k = 9 (coherence = -59.0). The curve drops at k = 3, then improves generally through k = 9 before becoming more variable. k = 9 is still more topics than needed for 100 articles and would likely split closely related content into near-identical groups. While k = 7 (-65.5), k = 8 (-62.4), and the statistical peak k = 9 (-59.0) all score higher than k = 6 (-66.1), at those values topics begin splitting closely related content into subtopics that are hard to tell apart.</p>
<p><strong>Interpretability:</strong> At k = 4, topics are broad and contain clearly unrelated terms mixed together, for example “cooking” and “pizza” appear in Topic 4 alongside weather adjacent terms like “smoke”, while “qep” appears in Topic 3 alongside industrial suppression terms like “liquid” and “chemical”. These are unrelated clusters of content that k = 4 fails to separate. At k = 6, each topic has a cleaner set of terms that point to a recognizable theme. At k = 8, some topics would start to split into very similar subtopics.</p>
<p><strong>Justification:</strong> k = 6 was selected. The coherence score at k = 6 is -66.1, which is not the highest, but at k = 7, k = 8, and the statistical peak k = 9, topics start splitting into subtopics that are difficult to distinguish from each other in practice. The 6 topics produced are each interpretable and distinct. The LDAvis map shows good separation overall, with the exception of Topics 4 and 5 which sit close together, both covering active fire response and recovery content and are naturally similar themes.</p>
</section>
<section id="final-model-and-top-terms-plot" class="level3">
<h3 class="anchored" data-anchor-id="final-model-and-top-terms-plot">3. Final Model and Top Terms Plot</h3>
<p>See Step 4 above, top 10 terms per topic plotted with β weights.</p>
</section>
<section id="document-topic-distributions" class="level3">
<h3 class="anchored" data-anchor-id="document-topic-distributions">4. Document-Topic Distributions</h3>
<p>See Step 6 above, θ distributions across 5 sample documents from the 100-article corpus. Document 4 is dominated by the Industrial Fire Risk and Technology topic, meaning that article focuses almost entirely on fire suppression systems and technical fire-prevention content. Documents 2, 3, and 5 are each dominated by the Seasonal Fire and Firefighter Response topic, pointing to active-fire-season coverage. Document 1 is the most spread across topics, meaning that article touches on several themes within a single piece.</p>
</section>
<section id="interpret-your-topics" class="level3">
<h3 class="anchored" data-anchor-id="interpret-your-topics">5. Interpret Your Topics</h3>
<p><strong>Topic 1: Scottish Fire Response:</strong> The top terms are “rescue”, “scottish”, “service”, “government”, “training”, “report”, “sfrs”, “firefighters”, “states”, and “blazes”. This topic covers articles about Scottish fire services, their operations, training programs, government reports, and responses to blazes. “sfrs” refers to the Scottish Fire and Rescue Service. The topic is geographically distinct because Scotland’s fire service operates under its own national structure, which generates a consistent set of terms across multiple articles.</p>
<p><strong>Topic 2: Climate &amp; Weather Conditions:</strong> The top terms are “conditions”, “wild”, “climate”, “time”, “cooking”, “years”, “solution”, “smoke”, “people”, and “support”. This topic groups articles that place wildfire in the context of climate and weather, dry conditions, rising temperatures, and seasonal patterns. “cooking” appears here because several articles about the Wild Fire pizza restaurant in Sunderland were pulled into the corpus by the broad search term “wild fire”, those articles have no connection to actual wildfires but share general vocabulary that landed them in this cluster.</p>
<p><strong>Topic 3: Vegetation &amp; Land Management:</strong> The top terms are “forest”, “management”, “areas”, “local”, “community”, “vegetation”, “controlled”, “lives”, “county”, and “risk”. This topic covers articles about managing land to reduce wildfire risk, controlled burns, clearing vegetation, protecting local communities and wildlife. It is the most prevention focused topic and deals with what happens before a fire starts rather than during or after.</p>
<p><strong>Topic 4: Seasonal Fire &amp; Firefighter Response:</strong> The top terms are “service”, “weather”, “wild”, “dry”, “april”, “firefighters”, “country”, “crews”, “emergency”, and “heat”. This topic groups articles about active fire seasons, crews responding to emergencies during dry spring and summer months. “april” and “dry” suggest several articles focus on the seasonal window when fire risk peaks. It covers frontline response from multiple countries.</p>
<p><strong>Topic 5: Disaster Recovery &amp; Community Impact:</strong> The top terms are “people”, “qep”, “news”, “home”, “emergency”, “content”, “california”, “state”, “recovery”, and “disaster”. This topic groups articles about what happens after a wildfire, evacuation, recovery efforts, and community rebuilding. “qep” refers to QEP, a company that donated cleaning supplies to hurricane and wildfire cleanup efforts, which appeared across multiple articles. “california” and “state” point to US-based recovery coverage.</p>
<p><strong>Topic 6: Industrial Fire Risk &amp; Technology:</strong> The top terms are “wild”, “property”, “system”, “liquid”, “chemical”, “network”, “anti-fire”, “area”, “spraying”, and “homes”. This topic covers industrial fire suppression technology, chemical spraying systems, anti-fire patents, and property protection networks. It sits near the center of the LDAvis map but uses highly technical and product specific vocabulary that sets it apart from the general wildfire news coverage in the other topics.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>